apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chongyejia-dev
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
images:
  - name: xiaozhi-retrieval-runtime
    newName: registry.cn-shanghai.aliyuncs.com/chongyejia/xiaozhi-retrieval-runtime
    newTag: 0.1.0-candidate
